import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { remoteStatus, updateFromRemote } from '../src/main/git-remote.ts'

const base = mkdtempSync(join(tmpdir(), 'praxis-git-remote-'))
const remote = join(base, 'origin.git'), seed = join(base, 'seed'), local = join(base, 'project')
const git = (cwd, ...args) => execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()
const identity = (cwd) => { git(cwd, 'config', 'user.name', 'Test'); git(cwd, 'config', 'user.email', 'test@example.com') }
const commit = (cwd, file, content) => { writeFileSync(join(cwd, file), content); git(cwd, 'add', '-A'); git(cwd, 'commit', '-m', content) }
try {
  git(base, 'init', '--bare', '--initial-branch=main', remote)
  git(base, 'init', '--initial-branch=main', seed)
  identity(seed)
  commit(seed, 'index.html', '<h1>Initial</h1>')
  git(seed, 'remote', 'add', 'origin', remote)
  git(seed, 'push', '-u', 'origin', 'main')
  git(base, 'clone', remote, local)
  identity(local)
  git(local, 'checkout', '-b', 'praxis/main')
  git(seed, 'checkout', '-b', 'feature/design')
  commit(seed, 'feature.txt', 'Remote feature')
  git(seed, 'push', '-u', 'origin', 'feature/design')
  git(seed, 'checkout', 'main')
  const cached = await remoteStatus(local)
  assert(!cached.branches.some((b) => b.branch === 'feature/design'))
  const fetched = await remoteStatus(local, true)
  assert(fetched.branches.some((b) => b.branch === 'feature/design'))
  assert(!fetched.branches.some((b) => b.branch === 'HEAD'))
  assert.equal(git(local, 'branch', '--show-current'), 'praxis/main', 'fetch must not switch branches')
  const pull = { action: 'pull', ref: 'refs/remotes/origin/main', expectedBranch: 'praxis/main' }
  commit(seed, 'upstream.txt', 'GitHub update')
  git(seed, 'push')
  writeFileSync(join(local, 'uncommitted.txt'), 'Keep me')
  assert.match((await updateFromRemote(local, pull)).message, /Commit or stash/)
  assert.equal(readFileSync(join(local, 'uncommitted.txt'), 'utf8'), 'Keep me')
  rmSync(join(local, 'uncommitted.txt'))
  assert.match((await updateFromRemote(local, pull, () => true)).message, /agents to finish/)
  assert.match((await updateFromRemote(local, { ...pull, expectedBranch: 'other' })).message, /branch changed/)
  mkdirSync(join(local, '.praxis'))
  writeFileSync(join(local, '.praxis/annotations.json'), '[]')
  git(local, 'remote', 'add', 'offline-backup', join(base, 'missing.git'))
  const first = await updateFromRemote(local, pull)
  git(local, 'remote', 'remove', 'offline-backup')
  assert(first.ok, first.message)
  assert(first.files.includes('upstream.txt'))
  assert.equal(readFileSync(join(local, 'upstream.txt'), 'utf8'), 'GitHub update')
  assert.equal((await updateFromRemote(local, pull)).changed, false)
  assert.equal(readFileSync(join(local, '.praxis/annotations.json'), 'utf8'), '[]')
  rmSync(join(local, '.praxis'), { recursive: true })

  // Diverged but compatible histories merge without losing the local commit.
  commit(local, 'local.txt', 'Local work')
  const localCommit = git(local, 'rev-parse', 'HEAD')
  commit(seed, 'another.txt', 'Another update')
  git(seed, 'push')
  const merged = await updateFromRemote(local, pull)
  assert(merged.ok, merged.message)
  git(local, 'merge-base', '--is-ancestor', localCommit, 'HEAD')
  assert.equal(readFileSync(join(local, 'local.txt'), 'utf8'), 'Local work')

  // Conflicts abort back to the exact starting commit and clean contents.
  commit(local, 'index.html', 'Local heading')
  const before = git(local, 'rev-parse', 'HEAD')
  commit(seed, 'index.html', 'Remote heading')
  git(seed, 'push')
  const conflict = await updateFromRemote(local, pull)
  assert(!conflict.ok)
  assert.equal(git(local, 'rev-parse', 'HEAD'), before)
  assert.equal(readFileSync(join(local, 'index.html'), 'utf8'), 'Local heading')
  assert.equal(git(local, 'status', '--porcelain'), '')
  assert(!existsSync(join(local, '.git/MERGE_HEAD')))
  assert(!(await updateFromRemote(local, { ...pull, ref: '--force' })).ok)
  const subdir = join(local, 'nested'); mkdirSync(subdir)
  assert(!(await updateFromRemote(subdir, pull)).ok, 'cannot mutate enclosing repository from a subfolder')
  rmSync(subdir, { recursive: true })

  const switched = await updateFromRemote(local, { ...pull, action: 'checkout', ref: 'refs/remotes/origin/feature/design' })
  assert(switched.ok, switched.message)
  assert.equal(switched.branch, 'feature/design')
  assert.equal(git(local, 'rev-parse', '--abbrev-ref', '@{upstream}'), 'origin/feature/design')
  assert.equal(readFileSync(join(local, 'feature.txt'), 'utf8'), 'Remote feature')
  const again = await updateFromRemote(local, { action: 'checkout', ref: 'refs/remotes/origin/feature/design', expectedBranch: 'feature/design' })
  assert(again.ok, again.message)
  assert.match(again.message, /Switched to local/)
  const existingMain = git(local, 'rev-parse', 'refs/heads/main')
  const reopenMain = await updateFromRemote(local, { action: 'checkout', ref: 'refs/remotes/origin/main', expectedBranch: 'feature/design' })
  assert(reopenMain.ok, reopenMain.message)
  assert.equal(git(local, 'rev-parse', 'HEAD'), existingMain, 'existing local main is not reset to remote')
  git(seed, 'push', 'origin', '--delete', 'feature/design')
  assert(!(await remoteStatus(local, true)).branches.some((b) => b.branch === 'feature/design'))
  console.log('GIT-REMOTE OK — fetch, prune, pull, tracking checkout, local commits, dirty/busy/stale guards, conflict rollback')
} finally { rmSync(base, { recursive: true, force: true }) }
