import assert from 'node:assert/strict'
import { _electron as electron } from 'playwright'
import electronPath from 'electron'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = process.cwd()
const base = mkdtempSync(join(tmpdir(), 'praxis-setup-ui-'))
const project = join(base, 'new-project')
const artifacts = join(root, 'test/artifacts')
mkdirSync(artifacts, { recursive: true })
let app
try {
  app = await electron.launch({ executablePath: electronPath, args: [join(root, 'out/main/index.js')], cwd: root,
    env: { ...process.env, PRAXIS_USER_DATA: join(base, 'profile'), PRAXIS_TEST_SKIP_INTRO: '1' } })
  const win = await app.firstWindow()
  await win.waitForSelector('.empty__open', { timeout: 15000 })
  await app.evaluate(({ ipcMain, dialog }, dest) => {
    dialog.showSaveDialog = async () => ({ canceled: false, filePath: dest })
    ipcMain.removeHandler('agent:open-project')
    ipcMain.handle('agent:open-project', () => ({ transcript: [] }))
    ipcMain.removeHandler('agent:send')
    ipcMain.handle('agent:send', (_event, text) => { globalThis.setupPrompt = text })
  }, project)
  const action = (name) => app.evaluate(({ BrowserWindow }, value) => BrowserWindow.getAllWindows()[0].webContents.send('menu:action', value), name)
  await action('new-project')
  await win.getByRole('dialog').waitFor()
  assert(!existsSync(project), 'no project files before choices')
  await win.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert(!existsSync(project), 'cancel writes nothing')
  await action('new-project')
  await win.getByRole('radio', { name: /^Svelte/ }).check()
  await win.getByRole('textbox', { name: /Anything already decided/ }).fill('Use npm. I am making a portfolio.')
  for (const [width, height] of [[390, 844], [768, 1024], [1440, 900]]) {
    await win.setViewportSize({ width, height })
    await win.getByRole('button', { name: 'Choose folder…' }).scrollIntoViewIfNeeded()
    const bounds = await win.getByRole('dialog').boundingBox()
    assert(bounds.x >= 0 && bounds.x + bounds.width <= width + 1, 'setup dialog fits viewport')
    await win.screenshot({ path: join(artifacts, `new-project-setup-${width}.png`) })
  }
  await win.screenshot({ path: join(artifacts, 'new-project-setup.png') })
  await win.getByRole('button', { name: 'Choose folder…' }).click()
  await win.waitForFunction((dir) => window.__praxisSession.getState().projectRoot === dir, project)
  for (let n = 0; n < 50 && !(await app.evaluate(() => globalThis.setupPrompt)); n++) await new Promise((r) => setTimeout(r, 100))
  const prompt = await app.evaluate(() => globalThis.setupPrompt)
  assert.match(prompt, /Svelte/)
  assert.match(prompt, /ask me/)
  assert.match(prompt, /Use npm/)
  assert(!existsSync(join(project, 'package.json')), 'custom setup does not create React/Vite')
  assert.equal(await win.evaluate((dir) => window.api.devServer.isRunning(dir), project), false)
  assert.equal(await win.getByText('Add a starter design-token palette?').count(), 0, 'empty setup stays focused on environment')
  await win.screenshot({ path: join(artifacts, 'new-project-chat.png') })

  const key = await win.evaluate(() => window.__praxisWorkspace.getState().activeKey)
  const event = (payload) => app.evaluate(({ BrowserWindow }, data) => BrowserWindow.getAllWindows()[0].webContents.send('agent:event', data), { projectKey: key, ...payload })
  const countRestarts = () => win.evaluate(() => window.__praxisLog.getState().lines.filter((line) => line.text.includes('Preview restarted at')).length)
  const waitRestarts = (count) => win.waitForFunction((expected) => window.__praxisLog.getState().lines.filter((line) => line.text.includes('Preview restarted at')).length >= expected, count, { timeout: 60000 })
  mkdirSync(join(project, 'framework'), { recursive: true })
  writeFileSync(join(project, '.npmrc'), 'audit=false\nfund=false\n')
  writeFileSync(join(project, 'framework/package.json'), JSON.stringify({ name: 'next', version: '1.0.0' }))
  writeFileSync(join(project, 'server.mjs'), `import http from 'node:http'; import fs from 'node:fs';
fs.writeFileSync('launch-args.json', JSON.stringify(process.argv.slice(2)));
http.createServer((req,res) => res.end('Environment ready')).listen(Number(process.env.PORT), '127.0.0.1', () => console.log('http://127.0.0.1:' + process.env.PORT));`)
  const manifest = (deps) => writeFileSync(join(project, 'package.json'), JSON.stringify({ name: 'setup-test', private: true, packageManager: 'npm@10.0.0', scripts: { dev: 'node server.mjs' }, dependencies: deps }))
  manifest({ next: 'file:./framework' })
  await event({ type: 'done' })
  await event({ type: 'isolation', state: 'parked', files: ['package.json'] })
  await new Promise((r) => setTimeout(r, 300))
  assert.equal(await countRestarts(), 0, 'done and parked changes must not launch')
  await event({ type: 'isolation', state: 'merged', files: ['package.json', 'next.config.ts'] })
  await waitRestarts(1)
  let entry = await win.evaluate(() => window.__praxisWorkspace.getState().projects[0])
  assert.equal(entry.launchSpec.framework, 'next')
  assert(existsSync(join(project, 'node_modules/next/package.json')), 'dependencies installed in live checkout')
  assert.equal(entry.launchSpec.command, 'npm run dev')
  const response = await app.evaluate(async (_electron, url) => (await fetch(url)).text(), entry.url)
  assert.equal(response, 'Environment ready')
  await event({ type: 'isolation', state: 'merged', files: ['src/App.tsx'] })
  await new Promise((r) => setTimeout(r, 300))
  assert.equal(await countRestarts(), 1, 'ordinary edits leave HMR running')

  mkdirSync(join(project, 'svelte-framework'))
  writeFileSync(join(project, 'svelte-framework/package.json'), JSON.stringify({ name: '@sveltejs/kit', version: '1.0.0' }))
  manifest({ '@sveltejs/kit': 'file:./svelte-framework' })
  await event({ type: 'isolation', state: 'merged', files: ['package.json', 'svelte.config.js'] })
  await waitRestarts(2)
  entry = await win.evaluate(() => window.__praxisWorkspace.getState().projects[0])
  assert.equal(entry.launchSpec.framework, 'sveltekit', 'migration must replace cached Next launch')
  assert(existsSync(join(project, 'node_modules/@sveltejs/kit/package.json')))
  await win.screenshot({ path: join(artifacts, 'project-setup-preview.png') })
  const shot = await app.evaluate(async ({ webContents }, url) => (await webContents.getAllWebContents().find((wc) => wc.getURL().startsWith(url)).capturePage()).toPNG().toString('base64'), entry.url)
  writeFileSync(join(artifacts, 'project-setup-native.png'), Buffer.from(shot, 'base64'))
  // Startup failure retains this chat; the retry can adopt a custom command.
  const broken = JSON.parse(readFileSync(join(project, 'package.json'), 'utf8'))
  broken.scripts.dev = 'node missing-server.mjs'
  writeFileSync(join(project, 'package.json'), JSON.stringify(broken))
  await event({ type: 'isolation', state: 'merged', files: ['package.json'] })
  await win.locator('.previewcard__errbar').waitFor({ timeout: 60000 })
  assert.equal(await win.evaluate(() => window.__praxisSession.getState().projectRoot), project, 'failed startup retains chat')
  await win.locator('.previewcard__errinput').fill('node server.mjs')
  await win.getByRole('button', { name: 'Run', exact: true }).click()
  await waitRestarts(3)
  entry = await win.evaluate(() => window.__praxisWorkspace.getState().projects[0])
  assert.equal(entry.launchSpec.customCommand, true)
  await event({ type: 'isolation', state: 'merged', files: ['svelte.config.js'] })
  await waitRestarts(4)
  entry = await win.evaluate(() => window.__praxisWorkspace.getState().projects[0])
  assert.equal(entry.launchSpec.command, 'node server.mjs', 'custom command survives re-detection')
  assert.equal(entry.launchSpec.framework, undefined, 'custom command must not receive framework-specific flags')

  await win.evaluate(() => window.__praxisSession.getState().setProjectRoot(null))
  await event({ type: 'isolation', state: 'merged', files: ['svelte.config.js'] })
  await new Promise((r) => setTimeout(r, 300))
  assert.equal(await countRestarts(), 4, 'background changes wait for activation')
  await win.evaluate((dir) => window.__praxisSession.getState().setProjectRoot(dir), project)
  await waitRestarts(5)

  // Opening an initially broken project still provides a repair conversation.
  const brokenProject = join(base, 'broken-project')
  mkdirSync(brokenProject)
  writeFileSync(join(brokenProject, 'package.json'), JSON.stringify({ name: 'broken-project' }))
  await app.evaluate(({ dialog }, dir) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [dir] })
  }, brokenProject)
  await action('open-project')
  await win.locator('.previewcard__errbar').waitFor({ timeout: 30000 })
  assert.equal(await win.evaluate(() => window.__praxisSession.getState().projectRoot), brokenProject)
  const brokenKey = await win.evaluate(() => window.__praxisWorkspace.getState().activeKey)
  rmSync(join(brokenProject, 'package.json'))
  writeFileSync(join(brokenProject, 'index.html'), '<h1>Static setup repaired</h1>')
  await event({ projectKey: brokenKey, type: 'isolation', state: 'merged', files: ['index.html'] })
  await waitRestarts(1)
  const repaired = await win.evaluate((key) => window.__praxisWorkspace.getState().projects.find((entry) => entry.key === key), brokenKey)
  assert.equal(repaired.launchSpec.framework, 'static', 'first HTML file launches an empty/unready preview')
  await win.evaluate((dir) => window.api.devServer.stop(dir), brokenProject)
  await win.evaluate((dir) => window.api.devServer.stop(dir), project)
  console.log('PROJECT-SETUP OK — cancel, empty chat, questions, landed installs, Next/Svelte re-detection, custom retry, background refresh, no premature restart')
} finally {
  await app?.close()
  rmSync(base, { recursive: true, force: true })
}
