import { checkChatIslands } from './smoke-islands'
import assert from 'node:assert/strict'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { NativeBridge } from './bridge'
import { dispatchIPC, serviceEvents } from './platform'
import { nativeWorkspace } from './workspace-runtime'
import { nativeChat } from './chat-runtime'
import { checkProjectSwitching } from './smoke-projects'
import { checkNativeSheets } from './smoke-sheets'
import { checkNativeChat } from './smoke-chat'
import { checkSelectionInput } from './smoke-input'
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve,ms))
export async function runNativeCoreSmoke(host: NativeBridge, fixture: string, root: string) {
  const invoke = (channel: string, ...args: any[]) => dispatchIPC('main',{type:'invoke',channel,args})
  const send = (channel: string, ...args: any[]) => dispatchIPC('main',{type:'send',channel,args})
  const page = (code: string) => host.request('evaluate',{view:'preview',code})
  const wait = async (check: () => Promise<any> | any, label: string, timeout=10000) => { const end=Date.now()+timeout; let last; while(Date.now()<end) { try { last=await check(); if(last)return last } catch(error){last=error}; await delay(80) }; throw new Error(`Native check timed out: ${label}; ${String(last)}`) }
  const inspect = (method: string, check: (s:any)=>boolean) => wait(async()=>{const state=await host.request(method);return check(state)&&state},method)
  const geometry = async (stage: string) => { const value = await host.request('layoutInspect'); console.log('Native geometry', stage, JSON.stringify(value)); assert.ok(value.windowHeight >= 550 && value.canvasHeight >= 450, `Collapsed workspace at ${stage}`) }
  await geometry('startup')
  const artifacts=join(root,'test/artifacts/native');mkdirSync(artifacts,{recursive:true})
  assert.deepEqual(await host.request('webViews'),['preview'])
  const welcome=await host.request('welcomeInspect');assert.ok(welcome.visible&&welcome.catFrames>=10)
  writeFileSync(join(artifacts,'welcome.png'),Buffer.from(await host.request('captureShell'),'base64'))
  writeFileSync(join(fixture,'native-style.tsx'), 'export function Fixture() { return <h1 style={{ opacity: 1 }}>Hello</h1> }')
  await host.request('shellPerform',{action:'open-project'})
  await wait(()=>nativeWorkspace.state.status.kind==='running','project running',30000)
  await wait(()=>page('!!document.querySelector("#native-title")'),'fixture loaded')
  // Reload must use WebKit's current document, including History API navigation.
  const originalURL = await page('location.href')
  writeFileSync(join(fixture, 'about.html'), readFileSync(join(fixture, 'index.html')))
  const route = new URL('/about.html?tab=details#section', originalURL).href
  await page(`(() => { history.pushState({}, '', ${JSON.stringify(route)}); window.reloadSentinel = true; return true })()`)
  host.emit('menu', { action: 'reload' })
  await wait(()=>page('!!document.querySelector("#native-title") && !window.reloadSentinel'),'reload completes')
  assert.equal(await page('location.href'), route, 'Reload preserves the current path, query and fragment')
  await page(`history.replaceState({}, '', ${JSON.stringify(originalURL)})`)
  console.log('Native reload preserves History API route, query and fragment.')
  await wait(()=>nativeChat.chats.get(nativeChat.active)?.ready,'native chat ready',30000)
  await inspect('composerInspect', s => s.welcomedChat)
  writeFileSync(join(artifacts,'composer-ready-beam.png'),Buffer.from(await host.request('captureComposer'),'base64'))
  await inspect('composerInspect', s => !s.readyBeam)
  assert.deepEqual(await host.request('composerIMECheck'), { marked: true, swallowed: false })
  await host.request('composerPerform', { text: '' })
  await inspect('composerInspect', s => s.text === '')
  const compactComposer = await host.request('composerInspect')
  const bottom = compactComposer.bounds.y + compactComposer.bounds.height
  await host.request('composerPerform', { text: Array(6).fill('A line of draft text').join('\n') + '\n' })
  const grownComposer = await inspect('composerInspect', s => s.bounds.height > compactComposer.bounds.height + 60)
  assert.equal(grownComposer.bounds.y + grownComposer.bounds.height, bottom, 'Composer grows upward from its anchored bottom')
  assert.ok(grownComposer.documentHeight <= grownComposer.inputHeight + 1, 'Uncapped draft fits without scrolling, including trailing newline')
  await host.request('composerPerform', { text: Array(80).fill('A long draft line').join('\n') })
  const cappedComposer = await inspect('composerInspect', s => s.bounds.height > grownComposer.bounds.height && s.documentHeight > s.inputHeight + 100)
  assert.ok(cappedComposer.bounds.height <= 368 && cappedComposer.bounds.height > grownComposer.bounds.height)
  writeFileSync(join(artifacts, 'composer-expanded.png'), Buffer.from(await host.request('captureComposer', { contentOnly: true }), 'base64'))
  await host.request('composerPerform', { text: 'wrap text '.repeat(20) })
  const wrappedComposer = await inspect('composerInspect', s => s.bounds.height > compactComposer.bounds.height && s.bounds.height < cappedComposer.bounds.height)
  assert.ok(wrappedComposer.documentHeight <= wrappedComposer.inputHeight + 1, 'Soft-wrapped draft fits before reaching the cap')
  await host.request('composerPerform', { text: '' })
  await inspect('composerInspect', s => s.text === '' && s.bounds.height === compactComposer.bounds.height)
  for (const clipboard of [{ image: 'png' }, { image: 'tiff' }, { paths: [join(fixture, 'index.html'), join(fixture, 'native-style.tsx')] }]) {
    assert.deepEqual(await host.request('composerPasteCheck', clipboard), { enabled: true, dispatched: true })
    const count = 'paths' in clipboard ? 2 : 1
    const previews = await inspect('composerInspect', s => s.attachments.length === count && s.enabled && s.text === '')
    assert.equal(previews.attachmentPreviews.count, count)
    assert.equal(previews.attachmentPreviews.images, 'paths' in clipboard ? 0 : 1)
    assert.equal(previews.attachmentPreviews.height, 108)
    assert.ok(previews.inputHeight >= compactComposer.inputHeight - 1)
    const attached = nativeChat.get(nativeChat.active).attachments
    if ('paths' in clipboard) assert.deepEqual(attached.map(a => a.path), clipboard.paths)
    else { assert.equal(attached[0].type, 'image/png'); assert.ok(attached[0].data.length > 0) }
    writeFileSync(join(artifacts, `paste-${'image' in clipboard ? clipboard.image : 'files'}.png`), Buffer.from(await host.request('captureShell'), 'base64'))
    for (let i = 0; i < count; i++) await host.request('composerPerform', { remove: 0 })
    await inspect('composerInspect', s => s.attachments.length === 0)
  }
  assert.deepEqual(await host.request('composerPasteCheck', { text: 'Pasted text に' }), { enabled: true, dispatched: true })
  await inspect('composerInspect', s => s.text === 'Pasted text に' && s.attachments.length === 0)
  await host.request('composerPerform', { text: '' })
  assert.deepEqual(await host.request('composerPasteCheck'), { enabled: false, dispatched: false })
  const previewFixture = join(artifacts, 'composer-ready-beam.png')
  await host.request('composerPerform', { files: [previewFixture, join(fixture, 'index.html'), previewFixture, previewFixture] })
  const mixed = await inspect('composerInspect', s => s.attachmentPreviews.count === 4)
  assert.equal(mixed.attachmentPreviews.images, 3)
  assert.ok(mixed.attachmentPreviews.documentWidth > mixed.attachmentPreviews.viewportWidth, 'Attachments scroll horizontally')
  writeFileSync(join(artifacts, 'composer-attachments.png'), Buffer.from(await host.request('captureComposer'), 'base64'))
  await host.request('composerPerform', { remove: 1 })
  const removed = await inspect('composerInspect', s => s.attachments.length === 3)
  assert.equal(removed.attachmentPreviews.images, 3, 'Remove targets the file between images')
  for (let i = 0; i < 3; i++) await host.request('composerPerform', { remove: 0 })
  await inspect('composerInspect', s => s.attachments.length === 0 && s.bounds.height === compactComposer.bounds.height)
  console.log('Native attachment thumbnails, file cards, overflow and removal passed.')
  await checkProjectSwitching(host, fixture, artifacts)
  assert.equal((await host.request('composerInspect')).readyBeam, false, 'Returning to a ready chat replayed its beam')
  await checkNativeSheets(host,nativeWorkspace.state.activeKey!,artifacts)
  await geometry('sheets')
  const shell=await inspect('shellInspect',s=>s.enabled.code)
  assert.equal(shell.outlineRows,shell.rows.filter((r:any)=>r.kind==='project').length)
  assert.deepEqual(shell.toolGroup,['code','layers','expand']);assert.deepEqual(shell.interactionGroup,['select-object','device'])
  assert.ok(shell.sidebarContainsTrafficLights&&shell.chatTitlePlain&&shell.publishStandard)
  await page(`(()=>{document.documentElement.style.backgroundColor='rgb(40,80,120)';document.body.style.backgroundColor='transparent'})()`)
  const surface=await inspect('previewSurfaceInspect',s=>Math.abs(s.red-40/255)<.02)
  assert.equal(surface.dividerHeight,surface.surfaceHeight)
  await inspect('shellInspect',s=>s.previewHeaderLightText)
  await page(`(()=>{document.documentElement.style.backgroundColor='rgb(250,250,250)'})()`)
  await inspect('shellInspect',s=>!s.previewHeaderLightText)
  await page(`(()=>{document.documentElement.style.removeProperty('background-color');document.body.style.removeProperty('background-color')})()`)
  await checkChatIslands(host, fixture, artifacts)
  const initial=await host.request('layoutInspect')
  for(const delta of [-30,30,-20,20])await host.request('dividerPerform',{delta})
  await inspect('layoutInspect',s=>Math.abs(s.width-initial.width)<1)
  await host.request('shellPerform',{action:'expand'});await inspect('layoutInspect',s=>s.fraction===0)
  await host.request('shellPerform',{action:'expand'});await inspect('layoutInspect',s=>s.fraction===1)
  await host.request('shellPerform',{action:'device'});await wait(()=>nativeWorkspace.active?.viewport==='mobile','mobile viewport')
  await host.request('shellPerform',{action:'device'});await wait(()=>nativeWorkspace.active?.viewport==='desktop','desktop viewport')
  await host.request('shellPerform',{action:'layers'});await inspect('layersInspect',s=>s.visible&&s.count>0)
  await host.request('shellPerform',{action:'layers'});await inspect('layersInspect',s=>!s.visible)
  await host.request('shellPerform',{action:'select-object'})
  await wait(()=>page(`document.documentElement.style.cursor==='crosshair'`),'select mode')
  if(process.env.PRAXIS_NATIVE_BACKGROUND_TEST==='1')console.log('SKIP real preview pointer gestures/animation timing: PRAXIS_NATIVE_BACKGROUND_TEST')
  else await checkSelectionInput(host)
  await invoke('preview:set-select-mode',false)
  assert.equal(await page('typeof window.api'), 'undefined')
  await assert.rejects(()=>dispatchIPC('preview',{type:'invoke',channel:'source:read',args:[fixture,'index.html:1:0']}))
  const layers=await invoke('layers:read'), heading=layers.nodes.find((n:any)=>n.id==='native-title');assert.ok(heading)
  await send('layers:select',{path:heading.path,fingerprint:{tag:heading.tag,source:heading.source}})
  await inspect('inspectorInspect',s=>!s.visible&&s.fields>2)
  serviceEvents.emit('event','preview:toolbar-action','props')
  const firstInspector=await inspect('inspectorInspect',s=>s.visible&&s.fields>2)
  serviceEvents.emit('event','preview:toolbar-action','props')
  await inspect('inspectorInspect',s=>!s.visible)
  serviceEvents.emit('event','preview:toolbar-action','props')
  await inspect('inspectorInspect',s=>s.visible)
  serviceEvents.emit('event','preview:element-picked',{tag:'h1',id:'native-title',classes:[],selector:'#native-title',source:'native-style.tsx:1:1',componentSource:null,text:'Hello',rect:{x:0,y:0,width:100,height:20},styles:{opacity:'1'}})
  const inspector=await inspect('inspectorInspect',s=>s.visible&&s.fields>2&&s.generation>firstInspector.generation)
  assert.deepEqual(await host.request('webViews'),['preview'])
  await wait(async()=> (await invoke('styles:read',['font-size']))?.values?.['font-size'], 'preview computed style after selection')
  await host.request('inspectorPerform',{action:{root:fixture,generation:inspector.generation,action:'apply',field:'style:opacity',value:'0.8'}})
  await wait(()=>readFileSync(join(fixture,'native-style.tsx'),'utf8').includes('0.8'),'native style source edit')
  await host.request('inspectorPerform',{action:{root:fixture,generation:inspector.generation,action:'close'}})
  await inspect('inspectorInspect',s=>!s.visible)
  const edited=await invoke('text:apply',fixture,{source:'index.html:3:1',text:'Edited through Praxis Native'});assert.ok(edited.applied)
  await wait(()=>page(`document.querySelector('#native-title')?.textContent==='Edited through Praxis Native'`),'managed reload')
  assert.ok((await invoke('edit:undo',fixture)).ok);assert.ok((await invoke('edit:redo',fixture)).ok)
  await host.request('composerPerform',{text:'Native draft'})
  await inspect('composerInspect',s=>s.text==='Native draft')
  const firstChat=nativeChat.active
  host.emit('shell-action',{action:'new-chat',project:nativeWorkspace.state.activeKey})
  await wait(()=>nativeChat.active!==firstChat,'new chat');await inspect('composerInspect',s=>s.text==='')
  await nativeWorkspace.command({type:'chat',key:nativeWorkspace.state.activeKey!,session:firstChat})
  await inspect('composerInspect',s=>s.text==='Native draft')
  nativeChat.event({type:'commands',projectKey:firstChat,commands:[{name:'native-fixture',description:'Native keyboard test',source:'project'}]})
  await host.request('composerPerform',{text:'/native'});await inspect('composerInspect',s=>s.skillListVisible&&s.skillCount>0)
  await host.request('composerPerform',{key:'Tab'});await inspect('composerInspect',s=>s.text==='/native-fixture ')
  await host.request('composerPerform',{text:''})
  await geometry('before popout')
  await invoke('source:popout',fixture,'index.html:3:1')
  const editor=await inspect('sourceInspect',s=>s.popped&&s.source==='index.html')
  await host.request('sourcePerform',{action:{root:fixture,action:'edit',source:'index.html',revision:100,text:editor.text+'\n<!-- native editor save -->'}})
  await inspect('sourceInspect',s=>s.dirty)
  await host.request('sourcePerform',{action:{root:fixture,action:'save'}})
  await inspect('sourceInspect',s=>!s.dirty&&!s.error)
  assert.ok(readFileSync(join(fixture,'index.html'),'utf8').includes('native editor save'))
  await host.request('sourcePerform',{action:{root:fixture,action:'dock'}});await inspect('sourceInspect',s=>s.visible&&!s.popped)
  await host.request('sourcePerform',{action:{root:fixture,action:'hide'}});await inspect('sourceInspect',s=>!s.visible)
  await geometry('after docking')
  mkdirSync(join(fixture,'.praxis'),{recursive:true})
  writeFileSync(join(fixture,'content.json'), JSON.stringify({title:'Native content',items:[{id:'one',name:'First item'}]}))
  writeFileSync(join(fixture,'.praxis/content-controls.json'), JSON.stringify({version:1,panels:[{id:'qa',file:'content.json',recipe:{version:1,id:'qa',title:'Native content editor',sections:[{id:'main',title:'Main',fields:[{key:'title',label:'Title',type:'text',required:true}]},{id:'items',title:'Items',collection:{key:'items',itemLabelKey:'name',defaults:{name:'New'},fields:[{key:'name',label:'Name',type:'text'}]}}]}}]}))
  serviceEvents.emit('event','content-controls:updated',{root:fixture})
  const content = await wait(async()=> (await host.request('contentInspect')).find((s:any)=>s.visible&&s.fields>2),'native content editor')
  const contentAction = (action: string, extra: any = {}) => host.emit('content-action',{documentID:content.id,root:fixture,generation:content.generation,action,...extra})
  contentAction('draft',{field:'main:title',value:'Saved in Swift'})
  contentAction('save')
  await wait(()=>JSON.parse(readFileSync(join(fixture,'content.json'),'utf8')).title==='Saved in Swift','native content save')
  await delay(200)
  writeFileSync(join(artifacts,'native-content.png'),Buffer.from(await host.request('captureContent',{documentID:content.id}),'base64'))
  contentAction('close');await wait(async()=>!(await host.request('contentInspect')).some((s:any)=>s.visible),'content close')
  await geometry('content')
  await checkNativeChat(host,join(artifacts,'swift-chat.png'))
  await host.request('previewInspector',{action:'show'});await inspect('previewInspector',s=>s.visible&&s.inspectable)
  await host.request('previewInspector',{action:'close'})
  writeFileSync(join(artifacts,'shell.png'),Buffer.from(await host.request('captureShell'),'base64'))
  assert.deepEqual(await host.request('webViews'),['preview'])
  console.log('NATIVE CORE PASS — no React/main/panel/editor WebViews; workspace, sheets, layout, native editing, streams and preview isolation.')
  if(process.argv.includes('--live')) {
    const provider=process.env.PRAXIS_NATIVE_TEST_PROVIDER||'claude'
    if(!['claude','codex'].includes(provider))throw new Error('Unsupported live provider')
    const options={provider,permissionMode:'bypassPermissions',...(provider==='claude'?{model:'haiku'}:{})}
    const restarted=await invoke('agent:restart-chat',fixture,nativeChat.active,options);assert.ok(restarted.ok)
    let done=false,error='';const listener=(channel:string,e:any)=>{if(channel==='agent:event'&&e.projectKey===nativeChat.active){if(e.type==='done')done=true;if(e.type==='error'){error=e.message;done=true}}};serviceEvents.on('event',listener)
    try { await host.request('composerPerform',{text:'Edit index.html. Replace the heading text "Edited through Praxis Native" with "NATIVE_AGENT_VERIFIED". Make the edit now.'});await inspect('composerInspect',s=>s.enabled);await host.request('composerPerform',{action:'send'});await wait(()=>done,'live provider',180000);assert.equal(error,'');await wait(()=>readFileSync(join(fixture,'index.html'),'utf8').includes('NATIVE_AGENT_VERIFIED'),'live file edit',30000) } finally {serviceEvents.off('event',listener)}
  }
}
