// Generated by scripts/generate-icons.py from the supplied SVGs.
export const iconPaths = {
  ArrowDown: [
    {"d": "M13 5V4H11V5H12H13ZM12 5H11V19H12H13V5H12Z", "fill": "currentColor"},
    {"d": "M19 12L12 19L5 12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  ArrowUp: [
    {"d": "M5 12L12 5L19 12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M11 19V20H13V19H12H11ZM12 19H13V5H12H11V19H12Z", "fill": "currentColor"},
  ],
  Brain: [
    {"d": "M12 18V5", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M15 13C14.1348 12.7471 13.3748 12.2206 12.834 11.4995C12.2932 10.7784 12.0005 9.90141 12 9C11.9995 9.90141 11.7068 10.7784 11.166 11.4995C10.6252 12.2206 9.8652 12.7471 9 13", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M17.598 6.49999C17.8281 6.10148 17.9635 5.65538 17.9936 5.19619C18.0237 4.737 17.9478 4.27704 17.7717 3.85189C17.5956 3.42674 17.324 3.04779 16.9781 2.74437C16.6321 2.44095 16.221 2.22119 15.7765 2.10209C15.332 1.98298 14.866 1.96773 14.4147 2.05751C13.9634 2.14729 13.5387 2.3397 13.1737 2.61984C12.8086 2.89998 12.5129 3.26036 12.3093 3.67308C12.1058 4.08581 12 4.53982 12 4.99999C12 4.53982 11.8942 4.08581 11.6907 3.67308C11.4871 3.26036 11.1914 2.89998 10.8263 2.61984C10.4613 2.3397 10.0366 2.14729 9.5853 2.05751C9.13396 1.96773 8.66803 1.98298 8.22353 2.10209C7.77904 2.22119 7.3679 2.44095 7.02193 2.74437C6.67596 3.04779 6.40442 3.42674 6.22833 3.85189C6.05224 4.27704 5.97632 4.737 6.00643 5.19619C6.03655 5.65538 6.17189 6.10148 6.402 6.49999", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M17.997 5.125C18.5848 5.27614 19.1305 5.55905 19.5928 5.95231C20.055 6.34557 20.4218 6.83887 20.6652 7.39485C20.9086 7.95082 21.0222 8.55489 20.9976 9.16131C20.973 9.76773 20.8107 10.3606 20.523 10.895", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M18 18C18.8805 18 19.7364 17.7094 20.4349 17.1734C21.1335 16.6373 21.6356 15.8858 21.8635 15.0353C22.0914 14.1848 22.0323 13.2829 21.6954 12.4694C21.3585 11.6559 20.7625 10.9763 20 10.536", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M19.967 17.483C20.0371 18.0252 19.9953 18.5761 19.8441 19.1015C19.693 19.627 19.4357 20.1158 19.0882 20.538C18.7407 20.9601 18.3104 21.3065 17.8238 21.5558C17.3372 21.8051 16.8046 21.9519 16.259 21.9873C15.7134 22.0227 15.1664 21.9459 14.6516 21.7616C14.1369 21.5773 13.6654 21.2894 13.2662 20.9158C12.8671 20.5421 12.5488 20.0906 12.331 19.5891C12.1132 19.0876 12.0006 18.5467 12 18C11.9994 18.5467 11.8868 19.0876 11.669 19.5891C11.4512 20.0906 11.1329 20.5421 10.7338 20.9158C10.3346 21.2894 9.86313 21.5773 9.34839 21.7616C8.83364 21.9459 8.28658 22.0227 7.74098 21.9873C7.19538 21.9519 6.66283 21.8051 6.17622 21.5558C5.68961 21.3065 5.25927 20.9601 4.91178 20.538C4.5643 20.1158 4.30703 19.627 4.15589 19.1015C4.00474 18.5761 3.96292 18.0252 4.033 17.483", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M6 18C5.1195 18 4.26361 17.7094 3.56507 17.1734C2.86653 16.6373 2.36437 15.8858 2.13648 15.0353C1.90858 14.1848 1.96768 13.2829 2.30462 12.4694C2.64155 11.6559 3.23748 10.9763 4 10.536", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M6.003 5.125C5.4152 5.27614 4.8695 5.55905 4.40723 5.95231C3.94496 6.34557 3.57824 6.83887 3.33484 7.39485C3.09145 7.95082 2.97776 8.55489 3.00239 9.16131C3.02702 9.76773 3.18932 10.3606 3.477 10.895", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Check: [
    {"d": "M20 6L9 17L4 12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  ChevronDown: [
    {"d": "M6 9L12 15L18 9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  ChevronLeft: [
    {"d": "M15 18L9 12L15 6", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  ChevronRight: [
    {"d": "M9 18L15 12L9 6", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Circle: [
    {"d": "M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Code2: [
    {"d": "M18 16L22 12L18 8", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M6 8L2 12L6 16", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M14.5 4L9.5 20", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Copy: [
    {"d": "M20 8H10C8.89543 8 8 8.89543 8 10V20C8 21.1046 8.89543 22 10 22H20C21.1046 22 22 21.1046 22 20V10C22 8.89543 21.1046 8 20 8Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M4 16C2.9 16 2 15.1 2 14V4C2 2.9 2.9 2 4 2H14C15.1 2 16 2.9 16 4", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Ellipsis: [
    {"d": "M12 13C12.5523 13 13 12.5523 13 12C13 11.4477 12.5523 11 12 11C11.4477 11 11 11.4477 11 12C11 12.5523 11.4477 13 12 13Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M19 13C19.5523 13 20 12.5523 20 12C20 11.4477 19.5523 11 19 11C18.4477 11 18 11.4477 18 12C18 12.5523 18.4477 13 19 13Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M5 13C5.55228 13 6 12.5523 6 12C6 11.4477 5.55228 11 5 11C4.44772 11 4 11.4477 4 12C4 12.5523 4.44772 13 5 13Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  FilePlus: [
    {"d": "M6 22C5.46957 22 4.96086 21.7893 4.58579 21.4142C4.21071 21.0391 4 20.5304 4 20V4C4 3.46957 4.21071 2.96086 4.58579 2.58579C4.96086 2.21072 5.46957 2 6 2H14C14.3166 1.99949 14.6301 2.06161 14.9225 2.18277C15.215 2.30394 15.4806 2.48176 15.704 2.706L19.292 6.294C19.5168 6.51751 19.6952 6.78335 19.8167 7.07616C19.9382 7.36898 20.0005 7.68297 20 8V20C20 20.5304 19.7893 21.0391 19.4142 21.4142C19.0391 21.7893 18.5304 22 18 22H6Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M14 2V7C14 7.26522 14.1054 7.51957 14.2929 7.70711C14.4804 7.89464 14.7348 8 15 8H20", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M9 15H15", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M12 18V12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  FileText: [
    {"d": "M6 22C5.46957 22 4.96086 21.7893 4.58579 21.4142C4.21071 21.0391 4 20.5304 4 20V4C4 3.46957 4.21071 2.96086 4.58579 2.58579C4.96086 2.21071 5.46957 2 6 2H14C14.3166 1.99949 14.6301 2.0616 14.9225 2.18277C15.215 2.30393 15.4806 2.48176 15.704 2.706L19.292 6.294C19.5168 6.51751 19.6952 6.78334 19.8167 7.07616C19.9382 7.36898 20.0005 7.68297 20 8V20C20 20.5304 19.7893 21.0391 19.4142 21.4142C19.0391 21.7893 18.5304 22 18 22H6Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M14 2V7C14 7.26522 14.1054 7.51957 14.2929 7.70711C14.4804 7.89464 14.7348 8 15 8H20", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M10 9H8", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M16 13H8", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M16 17H8", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Folder: [
    {"d": "M7.5 20 C7.5 20 4 20 4 20 C3.46957 20 2.96086 19.7893 2.58579 19.4142 C2.21071 19.0391 2 18.5304 2 18 C2 18 2 5 2 5 C2 4.46957 2.21071 3.96086 2.58579 3.58579 C2.96086 3.21071 3.46957 3 4 3 C4 3 7.93 3 7.93 3 C8.26111 3.00005 8.58702 3.08231 8.8785 3.2394 C9.16997 3.39648 9.41789 3.62347 9.6 3.9 C9.6 3.9 10.41 5.1 10.41 5.1 C10.594 5.37938 10.8451 5.60815 11.1403 5.76538 C11.4355 5.92261 11.7655 6.00328 12.1 6 C12.1 6 20 6 20 6 C20.5304 6 21.0391 6.21071 21.4142 6.58579 C21.7893 6.96086 22 7.46957 22 8 C22 8 22 9 22 9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M20.0048 20 C20.534 20 21.0415 19.7893 21.4156 19.4142 C21.7898 19.0391 22 18.5304 22 18 C22 18 22 8 22 8 C22 7.46957 21.7898 6.96086 21.4156 6.58579 C21.0415 6.21071 20.534 6 20.0048 6 C20.0048 6 3.99516 6.00092 3.99516 6.00092 C3.46601 6.00092 2.95853 6.20585 2.58437 6.58093 C2.2102 6.956 2 7.47049 2 8.00093 C2 8.00093 2.04839 18 2.04839 18 C2.04839 18.5304 2.25859 19.0391 2.63276 19.4142 C3.00692 19.7893 3.5144 20 4.04355 20 C4.04355 20 20.0048 20 20.0048 20 Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  FolderOpen: [
    {"d": "M7.50275 20 C7.50275 20 4.00275 20 4.00275 20 C3.47231 20 2.95256 19.7893 2.55783 19.4142 C2.1631 19.0391 1.92573 18.5304 1.89793 18 C1.89793 18 1.21663 5 1.21663 5 C1.18883 4.46957 1.37288 3.96086 1.7283 3.58579 C2.08372 3.21071 2.58138 3 3.11181 3 C3.11181 3 7.04181 3 7.04181 3 C7.37293 3.00005 7.70315 3.08231 8.00286 3.2394 C8.30257 3.39648 8.56238 3.62347 8.75898 3.9 C8.75898 3.9 9.63187 5.1 9.63187 5.1 C9.83047 5.37938 10.0936 5.60815 10.397 5.76538 C10.7005 5.92261 11.0347 6.00328 11.369 6 C11.369 6 19.269 6 19.269 6 C19.7995 6 20.3192 6.21071 20.714 6.58579 C21.1087 6.96086 21.3461 7.46957 21.3739 8 C21.3739 8 21.4263 9 21.4263 9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M19.8979 20 C20.4091 20 20.9539 19.8495 21.4125 19.5816 C21.871 19.3137 22.2058 18.9503 22.3431 18.5714 C22.3431 18.5714 23 11.5 23 11.5 C23 11 22.9976 10.6863 22.7332 10.4184 C22.4688 10.1505 22.0331 10 21.5219 10 C21.5219 10 8.05512 10.0007 8.05512 10.0007 C7.54393 10.0007 7.00062 10.147 6.54205 10.4149 C6.08349 10.6829 5.74724 11.0504 5.60993 11.4292 C5.60993 11.4292 3.06832 18.5714 3.06832 18.5714 C2.93102 18.9503 3.00241 19.3137 3.26679 19.5816 C3.53117 19.8495 3.96688 20 4.47808 20 C4.47808 20 19.8979 20 19.8979 20 Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Layers: [
    {"d": "M12.83 2.18C12.5694 2.06115 12.2864 1.99964 12 1.99964C11.7136 1.99964 11.4306 2.06115 11.17 2.18L2.6 6.08C2.42255 6.15824 2.27168 6.2864 2.16576 6.44885C2.05985 6.61131 2.00345 6.80106 2.00345 6.995C2.00345 7.18893 2.05985 7.37868 2.16576 7.54114C2.27168 7.7036 2.42255 7.83175 2.6 7.91L11.18 11.82C11.4406 11.9388 11.7236 12.0004 12.01 12.0004C12.2964 12.0004 12.5794 11.9388 12.84 11.82L21.42 7.92C21.5975 7.84175 21.7483 7.7136 21.8542 7.55114C21.9602 7.38868 22.0165 7.19893 22.0165 7.005C22.0165 6.81106 21.9602 6.62131 21.8542 6.45885C21.7483 6.2964 21.5975 6.16824 21.42 6.09L12.83 2.18Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M2 12C1.99953 12.1913 2.05392 12.3787 2.15672 12.5399C2.25952 12.7012 2.40642 12.8297 2.58 12.91L11.18 16.82C11.4392 16.9374 11.7205 16.9981 12.005 16.9981C12.2895 16.9981 12.5708 16.9374 12.83 16.82L21.41 12.92C21.587 12.8404 21.737 12.7111 21.8418 12.5477C21.9466 12.3844 22.0015 12.1941 22 12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M2 17C1.99953 17.1913 2.05392 17.3787 2.15672 17.5399C2.25952 17.7012 2.40642 17.8297 2.58 17.91L11.18 21.82C11.4392 21.9374 11.7205 21.9981 12.005 21.9981C12.2895 21.9981 12.5708 21.9374 12.83 21.82L21.41 17.92C21.587 17.8404 21.737 17.7111 21.8418 17.5477C21.9466 17.3844 22.0015 17.1941 22 17", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Loader2: [
    {"d": "M21 12C20.9999 13.9006 20.3981 15.7524 19.2809 17.2899C18.1637 18.8275 16.5885 19.9719 14.7809 20.5592C12.9733 21.1464 11.0262 21.1464 9.21864 20.559C7.41109 19.9716 5.83588 18.8271 4.71876 17.2895C3.60165 15.7519 2.99999 13.9001 3 11.9995C3.00001 10.0989 3.60171 8.24711 4.71884 6.7095C5.83598 5.17189 7.4112 4.02741 9.21877 3.44008C11.0263 2.85274 12.9734 2.85272 14.781 3.44", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Maximize2: [
    {"d": "M15 3H21V9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M13.2929 9.29289L12.5858 10L14 11.4142L14.7071 10.7071L14 10L13.2929 9.29289ZM21 3L20.2929 2.29289L13.2929 9.29289L14 10L14.7071 10.7071L21.7071 3.70711L21 3Z", "fill": "currentColor"},
    {"d": "M10.7071 14.7071L11.4142 14L10 12.5858L9.29289 13.2929L10 14L10.7071 14.7071ZM3 21L3.70711 21.7071L10.7071 14.7071L10 14L9.29289 13.2929L2.29289 20.2929L3 21Z", "fill": "currentColor"},
    {"d": "M9 21H3V15", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  MessageSquare: [
    {"d": "M22 17C22 17.5304 21.7893 18.0391 21.4142 18.4142C21.0391 18.7893 20.5304 19 20 19H6.828C6.29761 19.0001 5.78899 19.2109 5.414 19.586L3.212 21.788C3.1127 21.8873 2.9862 21.9549 2.84849 21.9823C2.71077 22.0097 2.56803 21.9956 2.43831 21.9419C2.30858 21.8881 2.1977 21.7971 2.11969 21.6804C2.04167 21.5637 2.00002 21.4264 2 21.286V5C2 4.46957 2.21071 3.96086 2.58579 3.58579C2.96086 3.21071 3.46957 3 4 3H20C20.5304 3 21.0391 3.21071 21.4142 3.58579C21.7893 3.96086 22 4.46957 22 5V17Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Minimize2: [
    {"d": "M21.7071 3.70711L22.4142 3L21 1.58579L20.2929 2.29289L21 3L21.7071 3.70711ZM14 10L14.7071 10.7071L21.7071 3.70711L21 3L20.2929 2.29289L13.2929 9.29289L14 10Z", "fill": "currentColor"},
    {"d": "M20 10H14V4", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M2.29289 20.2929L1.58579 21L3 22.4142L3.70711 21.7071L3 21L2.29289 20.2929ZM3 21L3.70711 21.7071L10.7071 14.7071L10 14L9.29289 13.2929L2.29289 20.2929L3 21Z", "fill": "currentColor"},
    {"d": "M4 14H10V20", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  MonitorSmartphone: [
    {"d": "M18 8V6C18 5.46957 17.7893 4.96086 17.4142 4.58579C17.0391 4.21071 16.5304 4 16 4H4C3.46957 4 2.96086 4.21071 2.58579 4.58579C2.21071 4.96086 2 5.46957 2 6V13C2 13.5304 2.21071 14.0391 2.58579 14.4142C2.96086 14.7893 3.46957 15 4 15H12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M10 19V15.04V18.19", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M7 19H12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M20 12H18C16.8954 12 16 12.8954 16 14V20C16 21.1046 16.8954 22 18 22H20C21.1046 22 22 21.1046 22 20V14C22 12.8954 21.1046 12 20 12Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  MousePointer2: [
    {"d": "M4.037 4.688C3.99753 4.59692 3.98636 4.49607 4.00494 4.39856C4.02352 4.30104 4.07099 4.21137 4.14118 4.14118C4.21137 4.07099 4.30104 4.02352 4.39856 4.00494C4.49607 3.98636 4.59692 3.99753 4.688 4.037L20.688 10.537C20.7853 10.5766 20.8676 10.6459 20.9233 10.735C20.979 10.8241 21.0052 10.9284 20.9982 11.0332C20.9913 11.1381 20.9515 11.238 20.8845 11.3189C20.8175 11.3998 20.7267 11.4576 20.625 11.484L14.501 13.064C14.155 13.153 13.8391 13.333 13.5862 13.5853C13.3333 13.8377 13.1527 14.1532 13.063 14.499L11.484 20.625C11.4576 20.7267 11.3998 20.8175 11.3189 20.8845C11.238 20.9515 11.1381 20.9913 11.0332 20.9982C10.9284 21.0052 10.8241 20.979 10.735 20.9233C10.6459 20.8676 10.5766 20.7853 10.537 20.688L4.037 4.688Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  PanelLeftClosed: [
    {"d": "M3 6 C3 4.34315 4.34315 3 6 3 C6 3 18 3 18 3 C19.6569 3 21 4.34315 21 6 C21 6 21 18 21 18 C21 19.6569 19.6569 21 18 21 C18 21 6 21 6 21 C4.34315 21 3 19.6569 3 18 C3 18 3 6 3 6 Z", "stroke": "currentColor", "strokeWidth": "2"},
    {"d": "M5 7 C5 6.44772 5.44772 6 6 6 C6.55228 6 7 6.44772 7 7 C7 7 7 17 7 17 C7 17.5523 6.55228 18 6 18 C5.44772 18 5 17.5523 5 17 C5 17 5 7 5 7 Z", "fill": "currentColor"},
  ],
  PanelLeftOpen: [
    {"d": "M3 6 C3 4.34315 4.34315 3 6 3 C6 3 18 3 18 3 C19.6569 3 21 4.34315 21 6 C21 6 21 18 21 18 C21 19.6569 19.6569 21 18 21 C18 21 6 21 6 21 C4.34315 21 3 19.6569 3 18 C3 18 3 6 3 6 Z", "stroke": "currentColor", "strokeWidth": "2"},
    {"d": "M5 6 C5 5.44772 5.44772 5 6 5 C6 5 11 5 11 5 C11 5 11 19 11 19 C11 19 6 19 6 19 C5.44772 19 5 18.5523 5 18 C5 18 5 6 5 6 Z", "fill": "currentColor"},
  ],
  Pencil: [
    {"d": "M21.174 6.812C21.7027 6.28342 21.9998 5.56647 21.9999 4.81885C22 4.07124 21.7031 3.35421 21.1745 2.8255C20.6459 2.29679 19.929 1.99971 19.1813 1.99962C18.4337 1.99952 17.7167 2.29642 17.188 2.825L3.842 16.174C3.60981 16.4055 3.43811 16.6905 3.342 17.004L2.021 21.356C1.99515 21.4425 1.9932 21.5343 2.01535 21.6219C2.03749 21.7094 2.08292 21.7892 2.14679 21.853C2.21067 21.9168 2.29062 21.9621 2.37815 21.9841C2.46569 22.0061 2.55755 22.004 2.644 21.978L6.997 20.658C7.31017 20.5628 7.59517 20.3921 7.827 20.161L21.174 6.812Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M15 5L19 9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Play: [
    {"d": "M5 5C4.9999 4.64809 5.09265 4.30238 5.26888 3.99779C5.44512 3.69319 5.69861 3.44049 6.00375 3.26519C6.30889 3.0899 6.65488 2.99822 7.00679 2.99942C7.3587 3.00061 7.70406 3.09464 8.008 3.272L20.005 10.27C20.3078 10.4457 20.5591 10.6977 20.7339 11.001C20.9088 11.3043 21.0009 11.6481 21.0012 11.9981C21.0015 12.3482 20.91 12.6922 20.7357 12.9957C20.5614 13.2993 20.3105 13.5518 20.008 13.728L8.008 20.728C7.70406 20.9054 7.3587 20.9994 7.00679 21.0006C6.65488 21.0018 6.30889 20.9101 6.00375 20.7348C5.69861 20.5595 5.44512 20.3068 5.26888 20.0022C5.09265 19.6976 4.9999 19.3519 5 19V5Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Plus: [
    {"d": "M5 12H19", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M12 5V19", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Save: [
    {"d": "M15.2 3C15.7275 3.00751 16.2307 3.22317 16.6 3.6L20.4 7.4C20.7768 7.76926 20.9925 8.27246 21 8.8V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V5C3 4.46957 3.21071 3.96086 3.58579 3.58579C3.96086 3.21071 4.46957 3 5 3H15.2Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M17 21V14C17 13.7348 16.8946 13.4804 16.7071 13.2929C16.5196 13.1054 16.2652 13 16 13H8C7.73478 13 7.48043 13.1054 7.29289 13.2929C7.10536 13.4804 7 13.7348 7 14V21", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M7 3V7C7 7 7.5 7.5 8 8H15L16 7V3", "stroke": "currentColor", "strokeWidth": "2", "strokeLinejoin": "round"},
  ],
  Search: [
    {"d": "M21 21L16.66 16.66", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M11 19C15.4183 19 19 15.4183 19 11C19 6.58172 15.4183 3 11 3C6.58172 3 3 6.58172 3 11C3 15.4183 6.58172 19 11 19Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  SlidersHorizontal: [
    {"d": "M10 5H3", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M12 19H3", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M14 3V7", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M16 17V21", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M21 12H12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M21 19H16", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M21 5H14", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M8 10V14", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M8 12H3", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Sparkles: [
    {"d": "M11.017 2.814C11.0598 2.5846 11.1816 2.37741 11.3611 2.22832C11.5406 2.07922 11.7666 1.9976 12 1.9976C12.2334 1.9976 12.4594 2.07922 12.6389 2.22832C12.8184 2.37741 12.9402 2.5846 12.983 2.814L14.034 8.372C14.1086 8.76715 14.3007 9.13062 14.585 9.41497C14.8694 9.69932 15.2329 9.89135 15.628 9.966L21.186 11.017C21.4154 11.0598 21.6226 11.1816 21.7717 11.3611C21.9208 11.5406 22.0024 11.7666 22.0024 12C22.0024 12.2334 21.9208 12.4594 21.7717 12.6389C21.6226 12.8184 21.4154 12.9402 21.186 12.983L15.628 14.034C15.2329 14.1086 14.8694 14.3007 14.585 14.585C14.3007 14.8694 14.1086 15.2329 14.034 15.628L12.983 21.186C12.9402 21.4154 12.8184 21.6226 12.6389 21.7717C12.4594 21.9208 12.2334 22.0024 12 22.0024C11.7666 22.0024 11.5406 21.9208 11.3611 21.7717C11.1816 21.6226 11.0598 21.4154 11.017 21.186L9.966 15.628C9.89135 15.2329 9.69932 14.8694 9.41497 14.585C9.13062 14.3007 8.76715 14.1086 8.372 14.034L2.814 12.983C2.5846 12.9402 2.37741 12.8184 2.22832 12.6389C2.07922 12.4594 1.9976 12.2334 1.9976 12C1.9976 11.7666 2.07922 11.5406 2.22832 11.3611C2.37741 11.1816 2.5846 11.0598 2.814 11.017L8.372 9.966C8.76715 9.89135 9.13062 9.69932 9.41497 9.41497C9.69932 9.13062 9.89135 8.76715 9.966 8.372L11.017 2.814Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M20 2V6", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M22 4H18", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M4 22C5.10457 22 6 21.1046 6 20C6 18.8954 5.10457 18 4 18C2.89543 18 2 18.8954 2 20C2 21.1046 2.89543 22 4 22Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  SquareArrowOutUpRight: [
    {"d": "M21 13V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V5C3 4.46957 3.21071 3.96086 3.58579 3.58579C3.96086 3.21071 4.46957 3 5 3H11", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M21 3L12 12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinejoin": "round"},
    {"d": "M15 3H21V9", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  SquarePen: [
    {"d": "M12 3H5C4.46957 3 3.96086 3.21071 3.58579 3.58579C3.21071 3.96086 3 4.46957 3 5V19C3 19.5304 3.21071 20.0391 3.58579 20.4142C3.96086 20.7893 4.46957 21 5 21H19C19.5304 21 20.0391 20.7893 20.4142 20.4142C20.7893 20.0391 21 19.5304 21 19V12", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M18.375 2.625C18.7728 2.22717 19.3124 2.00368 19.875 2.00368C20.4376 2.00368 20.9772 2.22717 21.375 2.625C21.7728 3.02282 21.9963 3.56239 21.9963 4.125C21.9963 4.68761 21.7728 5.22717 21.375 5.625L12.362 14.639C12.1246 14.8762 11.8312 15.0499 11.509 15.144L8.636 15.984C8.54995 16.0091 8.45874 16.0106 8.37191 15.9884C8.28508 15.9661 8.20583 15.9209 8.14245 15.8576C8.07907 15.7942 8.03389 15.7149 8.01165 15.6281C7.9894 15.5413 7.9909 15.45 8.016 15.364L8.856 12.491C8.95053 12.169 9.12454 11.8761 9.362 11.639L18.375 2.625Z", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Trash2: [
    {"d": "M10 11V17", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M14 11V17", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M19 6V20C19 20.5304 18.7893 21.0391 18.4142 21.4142C18.0391 21.7893 17.5304 22 17 22H7C6.46957 22 5.96086 21.7893 5.58579 21.4142C5.21071 21.0391 5 20.5304 5 20V6", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M3 6H21", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M8 6V4C8 3.46957 8.21071 2.96086 8.58579 2.58579C8.96086 2.21071 9.46957 2 10 2H14C14.5304 2 15.0391 2.21071 15.4142 2.58579C15.7893 2.96086 16 3.46957 16 4V6", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
  Undo2: [
    {"d": "M9 14L4 9L9 4", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M4 9H14.5C15.2223 9 15.9375 9.14226 16.6048 9.41866C17.272 9.69506 17.8784 10.1002 18.3891 10.6109C18.8998 11.1216 19.3049 11.728 19.5813 12.3952C19.8577 13.0625 20 13.7777 20 14.5C20 15.2223 19.8577 15.9375 19.5813 16.6048C19.3049 17.272 18.8998 17.8784 18.3891 18.3891C17.8784 18.8998 17.272 19.3049 16.6048 19.5813C15.9375 19.8577 15.2223 20 14.5 20H11", "stroke": "currentColor", "strokeWidth": "2", "strokeLinejoin": "round"},
  ],
  X: [
    {"d": "M18 6L6 18", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
    {"d": "M6 6L18 18", "stroke": "currentColor", "strokeWidth": "2", "strokeLinecap": "square", "strokeLinejoin": "round"},
  ],
} as const
