"""Compile the supplied SVG artwork into React path data and CSS morph targets.

Run with python3 scripts/generate-icons.py after updating assets/icons/*.svg.
The artwork stays unchanged; black paint becomes currentColor at runtime.
"""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'src/renderer/src/icons'
data = {}
for file in sorted((ROOT / 'src/renderer/src/assets/icons').glob('*.svg')):
    svg = ET.parse(file).getroot()
    paths = []
    for path in svg.iter('{http://www.w3.org/2000/svg}path'):
        attrs = {}
        for key, value in path.attrib.items():
            if key == 'style':
                continue  # supplied styles only repeat black paint at opacity 1
            key = re.sub(r'-([a-z])', lambda m: m[1].upper(), key)
            attrs[key] = 'currentColor' if value == 'black' else value
        paths.append(attrs)
    data[file.stem] = paths

# Convert straight segments to equivalent cubics so corresponding paths have
# identical command lists. Control points preserve the original geometry.
def cubic(d):
    tokens = re.findall(r'[A-Za-z]|-?\d*\.?\d+(?:[eE][-+]?\d+)?', d)
    out = []
    x = y = 0
    while tokens:
        command = tokens.pop(0)
        count = {'M': 2, 'C': 6, 'L': 2, 'H': 1, 'V': 1, 'Z': 0}[command]
        values = [float(tokens.pop(0)) for _ in range(count)]
        if command == 'M':
            x, y = values
        elif command in ('H', 'V', 'L'):
            nx, ny = (values[0], y) if command == 'H' else (x, values[0]) if command == 'V' else values
            command, values = 'C', [x, y, nx, ny, nx, ny]
            x, y = nx, ny
        elif command == 'C':
            x, y = values[-2:]
        out.append(command + ' '.join(format(v, '.8g') for v in values))
    return ' '.join(out)

# The sidebar export puts the panel first in Open and second in Closed.
data['PanelLeftOpen'] = [data['PanelLeftOpen'][1], data['PanelLeftOpen'][0]]
for name in ['Folder', 'FolderOpen', 'PanelLeftOpen', 'PanelLeftClosed']:
    for path in data[name]:
        path['d'] = cubic(path['d'])
for a, b in [('Folder', 'FolderOpen'), ('PanelLeftClosed', 'PanelLeftOpen')]:
    for left, right in zip(data[a], data[b]):
        assert re.findall('[A-Za-z]', left['d']) == re.findall('[A-Za-z]', right['d'])

DEST.mkdir(exist_ok=True)
text = '// Generated by scripts/generate-icons.py from the supplied SVGs.\n'
text += 'export const iconPaths = {\n'
for name, paths in data.items():
    text += f'  {name}: [\n' + ''.join('    ' + json.dumps(p) + ',\n' for p in paths) + '  ],\n'
text += '} as const\n'
(DEST / 'data.ts').write_text(text)

css = '/* Generated from the supplied SVG endpoints. */\n'
for family, closed, opened in [('folder', 'Folder', 'FolderOpen'), ('sidebar', 'PanelLeftClosed', 'PanelLeftOpen')]:
    for state, name in [('closed', closed), ('open', opened)]:
        for i, path in enumerate(data[name]):
            css += f'.praxis-icon--{family}[data-state="{state}"] > path:nth-of-type({i+1}) {{ d: path("{path["d"]}"); }}\n'
(DEST / 'morphs.css').write_text(css)
